spring.application.name=RecruitPro

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/recruit_pro
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# SQL log
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true